import Head from "next/head";
import { useEffect, useState } from "react";
import {
  FormControl,
  FormLabel,
  FormHelperText,
  Input,
  Button,
  RadioGroup,
  Heading,
  Radio,
  Text,
  Flex,
  Card,
  CardBody,
  HStack,
} from "@chakra-ui/react";
import { FaTwitter, FaLinkedin, FaGithub } from "react-icons/fa";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>GiftHub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Flex direction="column" align="center" justify="center">
          <div w={100}>
            <Text
              className={styles.title}
              fontSize={{ base: "40px", md: "50px", lg: "56px" }}
            >
              GiftHub 🎁
            </Text>
            <Text
              className={styles.description}
              fontSize={{ base: "20px", md: "24px", lg: "28px" }}
            >
              Gifting guide for n00bs
            </Text>
          </div>
        </Flex>
      </main>

      <footer className={styles.footer}>
        <Flex direction="column" align="center" justify="center">
          <div>Liked the Project ? Connect with me and let me know !</div>
          <br />
          <HStack>
            <a
              href="https://twitter.com/_heysahil/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Button colorScheme="twitter" leftIcon={<FaTwitter />} size="sm">
                Twitter
              </Button>
            </a>
            <a
              href="https://github.com/sahildotexe"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Button
                style={{ background: "black", color: "white" }}
                leftIcon={<FaGithub />}
                size="sm"
              >
                GitHub
              </Button>
            </a>

            <a
              href="https://www.linkedin.com/in/sahilkaling/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Button
                style={{ background: "#0A66C2", color: "white" }}
                leftIcon={<FaLinkedin />}
                size="sm"
              >
                LinkedIn
              </Button>
            </a>
          </HStack>
        </Flex>
      </footer>
    </div>
  );
}
